{
 "title": "F5 BNK Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "virtual_server",
    "label": "Virtual Server",
    "query": {
     "query": "label_values({f5_virtual_server_name=~\".*$tenant.*\"},f5_virtual_server_name)"
    }
   },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": {
     "query": "label_values({f5_pool_member_pool_name=~\".*$tenant.*\"},f5_pool_member_pool_name)"
    }
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(f5_virtual_server_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TMM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "F5 TMM CPU Usage 15 mins",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_tmm_f5_tmm_cpu_utilization_1min_per_10_2 / 10",
     "legendFormat": "TMM CPU {{f5_tmm_cpu}}"
    }
   ]
  },
  {
   "title": "F5 TMM Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (f5_tmm_f5_tmm_physmem_usage_bytes / f5_tmm_f5_tmm_physmem_limit_bytes)",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "F5 TMM L3 Interface Received Octets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * sum(rate(f5_tmm_f5_l3_interface_received_octets_total{f5_l3_interface_name!~\"^tmm.*\"}[$__rate_interval])) by (f5_l3_interface_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Virtual Server Clientside Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(f5_tmm_f5_virtual_server_clientside_connections_count_total{f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval]))",
     "legendFormat": "Total Connections"
    },
    {
     "expr": "sum(f5_tmm_f5_virtual_server_clientside_connections_current{f5_virtual_server_name=~\"$virtual_server\"})",
     "legendFormat": "Current Connections"
    }
   ]
  },
  {
   "title": "Tenant Backend Connections",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(f5_pool_member_pool_name, f5_pool_member_ip_address) (\r\n  f5_tmm_f5_pool_member_serverside_connections_current{f5_pool_member_pool_name=~\"$pool_name\"}\r\n)",
     "legendFormat": "Current Conn: {{f5_pool_member_pool_name}} - {{f5_pool_member_ip_address}}"
    },
    {
     "expr": "sum(f5_tmm_f5_pool_member_serverside_connections_max{f5_pool_member_pool_name=~\"$pool_name\"})",
     "legendFormat": "Total: ${tenant}"
    }
   ]
  },
  {
   "title": "Tenant Virtual Server Clientside Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(f5_tmm_f5_virtual_server_clientside_connections_current{f5_virtual_server_name=~\"$virtual_server\"}) by (f5_virtual_server_name)",
     "legendFormat": "Current Conn: {{f5_virtual_server_name}}"
    },
    {
     "expr": "sum(rate(f5_tmm_f5_virtual_server_clientside_connections_count_total{f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval]))",
     "legendFormat": "Total Conn: ${tenant}"
    }
   ]
  }
 ]
}