apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - milan1
                      - rome1
      containers:
      - image: ollama/ollama:0.3.5
        name: ollama
        env:
        - name: PRELOAD_MODELS
          value: "llama3.2:1b"
        - name: OLLAMA_KEEP_ALIVE
          value: "12h"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "for model in $PRELOAD_MODELS; do ollama run $model \"\"; done"]
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-app-svc
spec:
  ports:
  - port: 11434
    targetPort: 11434
  selector:
    app: ollama
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-node-port
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
      nodePort: 30434
