apiVersion: v1
kind: Service
metadata:
  name: nginx-app-nodeport
  namespace: blue
spec:
  type: NodePort
  selector:
    app: nginx-tcp
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080  # optional, omit to auto-assign
