network:
  version: 2
  renderer: networkd
  ethernets:

    enp193s0f0np0:
      virtual-function-count: 4
      dhcp4: no
      dhcp6: no
      mtu: 9000
    enp193s0f1np1:
      virtual-function-count: 4
      dhcp4: no
      dhcp6: no

    enp193s0f0v0:
      link: enp193s0f0np0
      dhcp4: no
      dhcp6: no
      mtu: 9000
      addresses:
        - 198.18.100.62/24
        - 2001::198:18:100:62/64
    enp193s0f0v1:
      link: enp193s0f0np0
      dhcp4: no
      dhcp6: no
      mtu: 9000
    enp193s0f0v2:
      link: enp193s0f0np0
      dhcp4: no
      dhcp6: no
      mtu: 9000
    enp193s0f0v3:
      link: enp193s0f0np0
      dhcp4: no
      dhcp6: no
      mtu: 9000
    enp193s0f1v0:
      link: enp193s0f1np1
      dhcp4: no
      dhcp6: no
      mtu: 9000

  vlans:
    external:
      id: 210
      link: enp193s0f0np0
      mtu: 8996
      addresses:
        - 192.0.2.62/24
        - 2001::192:0:2:62/64
